### PR TITLE
Azure ad authentication

### PR DESCRIPTION
**Pull request by cwkang1998**
Implemented customized azure ad authentication. However, more revisions and tests are to come.

### CODE REVIEW

**Review by pohzhiee — CHANGES_REQUESTED** [review]
no date_joined field?

**Comment by cwkang1998** [comment]
@pohzhiee The date_joined field is hidden for the user. Do you want me to expose it?

**Comment by cwkang1998** [comment]
@pohzhiee The date_joined field is hidden for the user. Do you want me to expose it?

**Comment by cwkang1998** [comment]
8652fc9a1a610e100a615da31463af28e70285c8 fixes the changes

**Review by pohzhiee — APPROVED** [review]

**Pull request merged**
