### PR TITLE
Society

### PR DESCRIPTION
**Pull request by jhchee**
-added participant table for attendance taking and feedback
-added pagination in settings.py

### CODE REVIEW

**Review by cwkang1998 — COMMENTED** [review]
Nicely done, However, me and desmond has decided on some changes so we are delaying pull request.

**Comment by jhchee** [comment]
Ok, sure.

**Review by cwkang1998 — CHANGES_REQUESTED** [review]
Is it possible for you to pull the newest commits and apply the changes? Sorry for the trouble.

**Comment by jhchee** [comment]
Alright

**Pull request closed without merging**
